/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package view;


import javax.swing.JButton;
import javax.swing.JComboBox;
import javax.swing.JLabel;
import javax.swing.JTable;
import javax.swing.JTextField;

/**
 *
 * @author Josep
 */
public class BuscarOrdemServicoView extends javax.swing.JInternalFrame {

    public BuscarOrdemServicoView() {
        initComponents();
    }

    public JButton getjButtonBuscar() {
        return jButtonBuscar;
    }

    public JButton getjButtonFechar() {
        return jButtonFechar;
    }

    public JButton getjButtonNovo() {
        return jButtonNovo;
    }

    public JButton getjButtonVisualizar() {
        return jButtonVisualizar;
    }

    public JTextField getjTextFieldBuscar() {
        return jTextFieldBuscar;
    }

    public JComboBox<String> getjComboBoxTipoBusca() {
        return jComboBoxTipoBusca;
    }

    public JLabel getjLabelObserverQTD() {
        return jLabelObserverQTD;
    }

    public JLabel getjLabelQtdRegistros() {
        return jLabelQtdRegistros;
    }

    public JTable getjTableOrdemServico() {
        return jTableOrdemServico;
    }

    public void setjTableOrdemServico(JTable jTableClientes) {
        this.jTableOrdemServico = jTableClientes;
    }

    public JButton getjButtonExcluir() {
        return jButtonExcluir;
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jButtonBuscar = new javax.swing.JButton();
        jButtonNovo = new javax.swing.JButton();
        jButtonVisualizar = new javax.swing.JButton();
        jButtonFechar = new javax.swing.JButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTableOrdemServico = new javax.swing.JTable();
        jLabelObserverQTD = new javax.swing.JLabel();
        jLabelQtdRegistros = new javax.swing.JLabel();
        jButtonExcluir = new javax.swing.JButton();
        jTextFieldBuscar = new javax.swing.JTextField();
        jComboBoxTipoBusca = new javax.swing.JComboBox<>();

        setClosable(true);
        setDefaultCloseOperation(javax.swing.WindowConstants.HIDE_ON_CLOSE);
        setTitle("Buscar Ordem de Serviço");
        setPreferredSize(new java.awt.Dimension(670, 500));
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setText("Busca por");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 25, 61, -1));

        jButtonBuscar.setText("Buscar");
        getContentPane().add(jButtonBuscar, new org.netbeans.lib.awtextra.AbsoluteConstraints(570, 20, -1, -1));

        jButtonNovo.setText("Novo");
        getContentPane().add(jButtonNovo, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 390, 100, -1));

        jButtonVisualizar.setText("Visualizar");
        getContentPane().add(jButtonVisualizar, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 390, 100, -1));

        jButtonFechar.setText("Fechar");
        getContentPane().add(jButtonFechar, new org.netbeans.lib.awtextra.AbsoluteConstraints(460, 390, 100, -1));

        jTableOrdemServico.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {

            }
        ));
        jTableOrdemServico.setColumnSelectionAllowed(true);
        jTableOrdemServico.getTableHeader().setReorderingAllowed(false);
        jScrollPane2.setViewportView(jTableOrdemServico);
        jTableOrdemServico.getColumnModel().getSelectionModel().setSelectionMode(javax.swing.ListSelectionModel.SINGLE_SELECTION);

        getContentPane().add(jScrollPane2, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 62, 634, 264));

        jLabelObserverQTD.setText("0");
        getContentPane().add(jLabelObserverQTD, new org.netbeans.lib.awtextra.AbsoluteConstraints(630, 340, -1, -1));

        jLabelQtdRegistros.setText("Quantidade de Ordem de Serviço Cadastrados:");
        getContentPane().add(jLabelQtdRegistros, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 340, -1, -1));

        jButtonExcluir.setText("Excluir");
        getContentPane().add(jButtonExcluir, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 390, 100, -1));
        getContentPane().add(jTextFieldBuscar, new org.netbeans.lib.awtextra.AbsoluteConstraints(204, 22, 350, -1));

        jComboBoxTipoBusca.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Todos", "Data", "Nome do Fiscal", "Número" }));
        getContentPane().add(jComboBoxTipoBusca, new org.netbeans.lib.awtextra.AbsoluteConstraints(75, 22, 123, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonBuscar;
    private javax.swing.JButton jButtonExcluir;
    private javax.swing.JButton jButtonFechar;
    private javax.swing.JButton jButtonNovo;
    private javax.swing.JButton jButtonVisualizar;
    private javax.swing.JComboBox<String> jComboBoxTipoBusca;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabelObserverQTD;
    private javax.swing.JLabel jLabelQtdRegistros;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTable jTableOrdemServico;
    private javax.swing.JTextField jTextFieldBuscar;
    // End of variables declaration//GEN-END:variables


}
