/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package view;

import javax.swing.JButton;
import javax.swing.JComboBox;
import javax.swing.JLabel;
import javax.swing.JTextField;


/**
 *
 * @author Josep
 */
public class ManterOrdemServicoView extends javax.swing.JInternalFrame {

    /**
     * Creates new form CadastrarEditarCliente
     */
    public ManterOrdemServicoView() {
        initComponents();
    }

    public JTextField getJTextField1() {
        return JTextField1;
    }

    public JTextField getJTextField2() {
        return JTextField2;
    }

    public JTextField getJTextField3() {
        return JTextField3;
    }

    public JTextField getJTextField4() {
        return JTextField4;
    }

    public JTextField getJTextField5() {
        return JTextField5;
    }

    public JTextField getJTextField6() {
        return JTextField6;
    }

    public JTextField getJTextField7() {
        return JTextField7;
    }

    public JTextField getJTextField8() {
        return JTextField8;
    }

    public JButton getjButtonAvancar() {
        return jButtonAvancar;
    }

    public JButton getjButtonCancelar() {
        return jButtonCancelar;
    }

    public JButton getjButtonEditar() {
        return jButtonEditar;
    }

    public JComboBox<String> getjComboBoxSituacao() {
        return jComboBoxSituacao;
    }

    public JLabel getjLabel1() {
        return jLabel1;
    }

    public JLabel getjLabel2() {
        return jLabel2;
    }

    public JLabel getjLabel3() {
        return jLabel3;
    }

    public JLabel getjLabel5() {
        return jLabel5;
    }

    public JLabel getjLabel6() {
        return jLabel6;
    }

    public JLabel getjLabel7() {
        return jLabel7;
    }

    public JLabel getjLabel8() {
        return jLabel8;
    }

    public JLabel getjLabelNumeroRevisao() {
        return jLabelNumeroRevisao;
    }

    public JLabel getjLabelSituacao() {
        return jLabelSituacao;
    }

    public JLabel getjLabelTitulo() {
        return jLabelTitulo;
    }

    public JLabel getjLabelTotalOrdemServidoReducoes() {
        return jLabelTotalOrdemServidoReducoes;
    }

    public JLabel getjLabelTotalReducaoMNSPDASS() {
        return jLabelTotalReducaoMNSPDASS;
    }

    public JLabel getjLabelTotalReducaoNMSGeral() {
        return jLabelTotalReducaoNMSGeral;
    }

    public JLabel getjLabelTotalReducoes() {
        return jLabelTotalReducoes;
    }

    public JLabel getjLabelValorPercentualTotalReducoes() {
        return jLabelValorPercentualTotalReducoes;
    }

    public JLabel getjLabelValorTotalOrdemServicoReducoes() {
        return jLabelValorTotalOrdemServicoReducoes;
    }

    public JLabel getjLabelValorTotalReducaoNMSGeral() {
        return jLabelValorTotalReducaoNMSGeral;
    }

    public JLabel getjLabelValorTotalReducaoNMSPDASS() {
        return jLabelValorTotalReducaoNMSPDASS;
    }

    public JLabel getjLabelValorTotalReducoes() {
        return jLabelValorTotalReducoes;
    }

    public JLabel getjLabel4() {
        return jLabel4;
    }

    public JLabel getjLabelPercentualTotalReducoes() {
        return jLabelPercentualTotalReducoes;
    }

       
    
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jButtonAvancar = new javax.swing.JButton();
        jButtonCancelar = new javax.swing.JButton();
        jButtonEditar = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        jPanel2 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        JTextField3 = new javax.swing.JTextField();
        JTextField2 = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        JTextField1 = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabelTotalReducaoNMSGeral = new javax.swing.JLabel();
        JTextField4 = new javax.swing.JTextField();
        JTextField5 = new javax.swing.JTextField();
        JTextField8 = new javax.swing.JTextField();
        jLabelValorTotalReducaoNMSGeral = new javax.swing.JLabel();
        jLabelTotalReducaoMNSPDASS = new javax.swing.JLabel();
        jLabelValorTotalReducaoNMSPDASS = new javax.swing.JLabel();
        jLabelTotalReducoes = new javax.swing.JLabel();
        jLabelValorTotalReducoes = new javax.swing.JLabel();
        jLabelPercentualTotalReducoes = new javax.swing.JLabel();
        jLabelValorPercentualTotalReducoes = new javax.swing.JLabel();
        jLabelTotalOrdemServidoReducoes = new javax.swing.JLabel();
        jLabelValorTotalOrdemServicoReducoes = new javax.swing.JLabel();
        jLabelTitulo = new javax.swing.JLabel();
        jLabelSituacao = new javax.swing.JLabel();
        jComboBoxSituacao = new javax.swing.JComboBox<>();
        jLabelNumeroRevisao = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        JTextField6 = new javax.swing.JTextField();
        JTextField7 = new javax.swing.JTextField();

        setClosable(true);
        setDefaultCloseOperation(javax.swing.WindowConstants.DO_NOTHING_ON_CLOSE);
        setPreferredSize(new java.awt.Dimension(670, 500));

        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jButtonAvancar.setText("Avançar");
        jPanel1.add(jButtonAvancar, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 20, 120, -1));

        jButtonCancelar.setText("Cancelar");
        jPanel1.add(jButtonCancelar, new org.netbeans.lib.awtextra.AbsoluteConstraints(440, 20, 120, -1));

        jButtonEditar.setText("Editar");
        jPanel1.add(jButtonEditar, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 20, 120, -1));

        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel2.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel2.setText("JLabel2");
        jPanel2.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 107, -1, -1));
        jPanel2.add(JTextField3, new org.netbeans.lib.awtextra.AbsoluteConstraints(299, 145, 330, -1));
        jPanel2.add(JTextField2, new org.netbeans.lib.awtextra.AbsoluteConstraints(299, 107, 330, -1));

        jLabel1.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel1.setText("JLabel1");
        jPanel2.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 66, -1, 23));

        jLabel3.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel3.setText("JLabel3");
        jPanel2.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 145, -1, -1));
        jPanel2.add(JTextField1, new org.netbeans.lib.awtextra.AbsoluteConstraints(299, 69, 330, -1));

        jLabel4.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel4.setText("JLabel4");
        jPanel2.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 183, -1, -1));

        jLabel5.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel5.setText("JLabel5");
        jPanel2.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 221, -1, -1));

        jLabel8.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel8.setText("JLabel8");
        jPanel2.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 335, -1, -1));

        jLabelTotalReducaoNMSGeral.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabelTotalReducaoNMSGeral.setText("Valor Total da Redução do NMS Geral (R$):");
        jPanel2.add(jLabelTotalReducaoNMSGeral, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 373, -1, -1));
        jPanel2.add(JTextField4, new org.netbeans.lib.awtextra.AbsoluteConstraints(299, 183, 330, -1));
        jPanel2.add(JTextField5, new org.netbeans.lib.awtextra.AbsoluteConstraints(299, 221, 330, -1));
        jPanel2.add(JTextField8, new org.netbeans.lib.awtextra.AbsoluteConstraints(299, 335, 330, -1));

        jLabelValorTotalReducaoNMSGeral.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabelValorTotalReducaoNMSGeral.setText("VALOR");
        jPanel2.add(jLabelValorTotalReducaoNMSGeral, new org.netbeans.lib.awtextra.AbsoluteConstraints(325, 373, -1, -1));

        jLabelTotalReducaoMNSPDASS.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabelTotalReducaoMNSPDASS.setText("Valor Total Redução do NMS PDASS (R$):");
        jPanel2.add(jLabelTotalReducaoMNSPDASS, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 408, -1, -1));

        jLabelValorTotalReducaoNMSPDASS.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabelValorTotalReducaoNMSPDASS.setText("VALOR");
        jPanel2.add(jLabelValorTotalReducaoNMSPDASS, new org.netbeans.lib.awtextra.AbsoluteConstraints(316, 408, -1, -1));

        jLabelTotalReducoes.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabelTotalReducoes.setText("Valor Total das Reduções (R$): ");
        jPanel2.add(jLabelTotalReducoes, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 443, -1, -1));

        jLabelValorTotalReducoes.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabelValorTotalReducoes.setText("VALOR");
        jPanel2.add(jLabelValorTotalReducoes, new org.netbeans.lib.awtextra.AbsoluteConstraints(246, 443, -1, -1));

        jLabelPercentualTotalReducoes.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabelPercentualTotalReducoes.setText("Percentual Total das Reduções (%): ");
        jPanel2.add(jLabelPercentualTotalReducoes, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 478, -1, -1));

        jLabelValorPercentualTotalReducoes.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabelValorPercentualTotalReducoes.setText("VALOR");
        jPanel2.add(jLabelValorPercentualTotalReducoes, new org.netbeans.lib.awtextra.AbsoluteConstraints(281, 478, -1, -1));

        jLabelTotalOrdemServidoReducoes.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabelTotalOrdemServidoReducoes.setText("Valor Total da Ordem de Serviço com Reduções (R$): ");
        jPanel2.add(jLabelTotalOrdemServidoReducoes, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 513, -1, -1));

        jLabelValorTotalOrdemServicoReducoes.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabelValorTotalOrdemServicoReducoes.setText("VALOR");
        jPanel2.add(jLabelValorTotalOrdemServicoReducoes, new org.netbeans.lib.awtextra.AbsoluteConstraints(398, 513, -1, -1));

        jLabelTitulo.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabelTitulo.setText("JLabel");
        jPanel2.add(jLabelTitulo, new org.netbeans.lib.awtextra.AbsoluteConstraints(296, 0, -1, 23));

        jLabelSituacao.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabelSituacao.setText("Situação");
        jPanel2.add(jLabelSituacao, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 25, -1, 23));

        jComboBoxSituacao.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Aberta", "Em execução", "Fechada", "Revisão", "Paga" }));
        jPanel2.add(jComboBoxSituacao, new org.netbeans.lib.awtextra.AbsoluteConstraints(299, 28, 186, -1));

        jLabelNumeroRevisao.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabelNumeroRevisao.setText("JLabelSituacao");
        jPanel2.add(jLabelNumeroRevisao, new org.netbeans.lib.awtextra.AbsoluteConstraints(503, 25, -1, 23));

        jLabel6.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel6.setText("JLabel6");
        jPanel2.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 259, -1, -1));

        jLabel7.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel7.setText("JLabel7");
        jPanel2.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 297, -1, -1));
        jPanel2.add(JTextField6, new org.netbeans.lib.awtextra.AbsoluteConstraints(299, 259, 330, -1));
        jPanel2.add(JTextField7, new org.netbeans.lib.awtextra.AbsoluteConstraints(299, 297, 330, -1));

        jScrollPane1.setViewportView(jPanel2);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 684, Short.MAX_VALUE)
            .addComponent(jScrollPane1)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 370, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 65, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(20, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField JTextField1;
    private javax.swing.JTextField JTextField2;
    private javax.swing.JTextField JTextField3;
    private javax.swing.JTextField JTextField4;
    private javax.swing.JTextField JTextField5;
    private javax.swing.JTextField JTextField6;
    private javax.swing.JTextField JTextField7;
    private javax.swing.JTextField JTextField8;
    private javax.swing.JButton jButtonAvancar;
    private javax.swing.JButton jButtonCancelar;
    private javax.swing.JButton jButtonEditar;
    private javax.swing.JComboBox<String> jComboBoxSituacao;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabelNumeroRevisao;
    private javax.swing.JLabel jLabelPercentualTotalReducoes;
    private javax.swing.JLabel jLabelSituacao;
    private javax.swing.JLabel jLabelTitulo;
    private javax.swing.JLabel jLabelTotalOrdemServidoReducoes;
    private javax.swing.JLabel jLabelTotalReducaoMNSPDASS;
    private javax.swing.JLabel jLabelTotalReducaoNMSGeral;
    private javax.swing.JLabel jLabelTotalReducoes;
    private javax.swing.JLabel jLabelValorPercentualTotalReducoes;
    private javax.swing.JLabel jLabelValorTotalOrdemServicoReducoes;
    private javax.swing.JLabel jLabelValorTotalReducaoNMSGeral;
    private javax.swing.JLabel jLabelValorTotalReducaoNMSPDASS;
    private javax.swing.JLabel jLabelValorTotalReducoes;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    // End of variables declaration//GEN-END:variables
}
