/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package view;

import javax.swing.JDesktopPane;
import javax.swing.JMenu;
import javax.swing.JMenuItem;
import javax.swing.JRadioButtonMenuItem;

/**
 *
 * @author Josep
 */
public class TelaPrincipalView extends javax.swing.JFrame {

    /**
     * Creates new form TelaPrincipal
     */
    public TelaPrincipalView() {
        initComponents();
    }

    public JDesktopPane getjDesktopPanePrincipal() {
        return jDesktopPanePrincipal;
    }

    public JMenuItem getjMenuItemBuscar() {
        return jMenuItemBuscar;
    }

    public JMenuItem getjMenuItemGraficoLinha() {
        return jMenuItemGraficoLinha;
    }

    public JMenuItem getjMenuItemExit() {
        return jMenuItemExit;
    }

    public JMenuItem getjMenuItemLogout() {
        return jMenuItemLogout;
    }

    public JMenu getjMenuUsuario() {
        return jMenuUsuario;
    }

    public JRadioButtonMenuItem getjRadioButtonMenuItemJSON() {
        return jRadioButtonMenuItemJSON;
    }

    public JRadioButtonMenuItem getjRadioButtonMenuItemXML() {
        return jRadioButtonMenuItemXML;
    }
 
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        jDesktopPanePrincipal = new javax.swing.JDesktopPane();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        jMenuItemBuscar = new javax.swing.JMenuItem();
        jMenu2 = new javax.swing.JMenu();
        jMenuItemGraficoLinha = new javax.swing.JMenuItem();
        jMenu4 = new javax.swing.JMenu();
        jRadioButtonMenuItemXML = new javax.swing.JRadioButtonMenuItem();
        jRadioButtonMenuItemJSON = new javax.swing.JRadioButtonMenuItem();
        jMenuUsuario = new javax.swing.JMenu();
        jMenuItemLogout = new javax.swing.JMenuItem();
        jMenuItemExit = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Cadastro de Cliente");
        setState(6);

        javax.swing.GroupLayout jDesktopPanePrincipalLayout = new javax.swing.GroupLayout(jDesktopPanePrincipal);
        jDesktopPanePrincipal.setLayout(jDesktopPanePrincipalLayout);
        jDesktopPanePrincipalLayout.setHorizontalGroup(
            jDesktopPanePrincipalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 1182, Short.MAX_VALUE)
        );
        jDesktopPanePrincipalLayout.setVerticalGroup(
            jDesktopPanePrincipalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 620, Short.MAX_VALUE)
        );

        jMenu1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/client_account_template.png"))); // NOI18N
        jMenu1.setText("Ordem de Serviço");

        jMenuItemBuscar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/search.png"))); // NOI18N
        jMenuItemBuscar.setText("Buscar/Editar");
        jMenu1.add(jMenuItemBuscar);

        jMenuBar1.add(jMenu1);

        jMenu2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/Graph.png"))); // NOI18N
        jMenu2.setText("Gráfico");

        jMenuItemGraficoLinha.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/1.png"))); // NOI18N
        jMenuItemGraficoLinha.setText("Gráfico de Linha");
        jMenu2.add(jMenuItemGraficoLinha);

        jMenuBar1.add(jMenu2);

        jMenu4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/LOG File Extension.png"))); // NOI18N
        jMenu4.setText("Opção de LOG");

        buttonGroup1.add(jRadioButtonMenuItemXML);
        jRadioButtonMenuItemXML.setSelected(true);
        jRadioButtonMenuItemXML.setText("Salvar LOG em XML");
        jRadioButtonMenuItemXML.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/xml.png"))); // NOI18N
        jMenu4.add(jRadioButtonMenuItemXML);

        buttonGroup1.add(jRadioButtonMenuItemJSON);
        jRadioButtonMenuItemJSON.setText("Salvar LOG em JSON");
        jRadioButtonMenuItemJSON.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/json.png"))); // NOI18N
        jMenu4.add(jRadioButtonMenuItemJSON);

        jMenuBar1.add(jMenu4);

        jMenuUsuario.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/User (1).png"))); // NOI18N
        jMenuUsuario.setText("Usuário:");

        jMenuItemLogout.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/logout.png"))); // NOI18N
        jMenuItemLogout.setText("Logout");
        jMenuUsuario.add(jMenuItemLogout);

        jMenuItemExit.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/exit.png"))); // NOI18N
        jMenuItemExit.setText("Sair do Sistema");
        jMenuUsuario.add(jMenuItemExit);

        jMenuBar1.add(jMenuUsuario);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jDesktopPanePrincipal)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jDesktopPanePrincipal)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JDesktopPane jDesktopPanePrincipal;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenu jMenu4;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuItem jMenuItemBuscar;
    private javax.swing.JMenuItem jMenuItemExit;
    private javax.swing.JMenuItem jMenuItemGraficoLinha;
    private javax.swing.JMenuItem jMenuItemLogout;
    private javax.swing.JMenu jMenuUsuario;
    private javax.swing.JRadioButtonMenuItem jRadioButtonMenuItemJSON;
    private javax.swing.JRadioButtonMenuItem jRadioButtonMenuItemXML;
    // End of variables declaration//GEN-END:variables
}
